<a href="https://colab.research.google.com/github/LatiefDataVisionary/scikit-learn-with-indonesia-belajar/blob/main/SKLearn_07_Regression_dengan_KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SKLearn 07: Regression dengan KNN | K-Nearest Neighbours | Belajar Machine Learning Dasar**


### **Sample Dataset**

In [3]:
import pandas as pd

sensus = {'tinggi': [156, 170, 183, 191, 158, 170, 181, 175, 164],
          'jk': ['pria', 'pria', 'pria', 'pria', 'wanita', 'wanita', 'wanita', 'wanita', 'wanita'],
          'berat': [64, 86, 84, 80, 49, 59, 67, 54, 67]}

sensus_df = pd.DataFrame(sensus)
sensus_df

tinggi      jk  berat
0     156    pria     64
1     170    pria     86
2     183    pria     84
3     191    pria     80
4     158  wanita     49
5     170  wanita     59
6     181  wanita     67
7     175  wanita     54
8     164  wanita     67

## **Regression dengan KNN**

### **Features & Target**

In [8]:
import numpy as np

X_train = np.array(sensus_df[['tinggi', 'jk']])
y_train = np.array(sensus_df['berat'])

print(f'X_trains: \n{X_train}')
print(f'\ny_train: {y_train}')

X_trains: 
[[156 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [158 'wanita']
 [170 'wanita']
 [181 'wanita']
 [175 'wanita']
 [164 'wanita']]

y_train: [64 86 84 80 49 59 67 54 67]


### **Preprocess dataset: Konversi Label menjadi Numerik Biner**

In [9]:
X_train_transposed = np.transpose(X_train)

print(f'X_train: \n{X_train}')
print(f'\nX_train_transposed: \n{X_train_transposed}')

X_train: 
[[156 'pria']
 [170 'pria']
 [183 'pria']
 [191 'pria']
 [158 'wanita']
 [170 'wanita']
 [181 'wanita']
 [175 'wanita']
 [164 'wanita']]

X_train_transposed: 
[[156 170 183 191 158 170 181 175 164]
 ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita'
  'wanita']]


In [11]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
jk_binarised = lb.fit_transform(X_train_transposed[1])

print(f'jk: {X_train_transposed[1]}\n')
print(f'jk_binarised: \n{jk_binarised}')

jk: ['pria' 'pria' 'pria' 'pria' 'wanita' 'wanita' 'wanita' 'wanita' 'wanita']

jk_binarised: 
[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [12]:
jk_binarised = jk_binarised.flatten()
jk_binarised

array([0, 0, 0, 0, 1, 1, 1, 1, 1])

In [13]:
X_train_transposed[1] = jk_binarised
X_train = X_train_transposed.transpose()

print(f'X_train_transposed: \n{X_train_transposed}')
print(f'X_train: \n{X_train}')

X_train_transposed: 
[[156 170 183 191 158 170 181 175 164]
 [0 0 0 0 1 1 1 1 1]]
X_train: 
[[156 0]
 [170 0]
 [183 0]
 [191 0]
 [158 1]
 [170 1]
 [181 1]
 [175 1]
 [164 1]]
